openapi: 3.0.3
info:
  title: Materialize Cloud
  version: 0.1.0
paths:
  /api/deployments:
    get:
      operationId: deploymentsList
      description: List the available deployments.
      tags:
      - deployments
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deployment'
          description: ''
    post:
      operationId: deploymentsCreate
      description: Create a new deployment.
      tags:
      - deployments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeploymentRequest'
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
          description: ''
  /api/deployments/{id}:
    get:
      operationId: deploymentsRetrieve
      description: Fetch details about a single deployment.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - deployments
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
          description: ''
    put:
      operationId: deploymentsUpdate
      description: Update a deployment.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - deployments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeploymentRequest'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
          description: ''
    patch:
      operationId: deploymentsPartialUpdate
      description: Partially update a deployment.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - deployments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedDeploymentRequest'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
          description: ''
    delete:
      operationId: deploymentsDestroy
      description: Destroy a deployment.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - deployments
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /api/deployments/{id}/certs:
    get:
      operationId: deploymentsCertsRetrieve
      description: |-
        Retrieve a TLS certificate bundle for a deployment.

        The TLS certificate bundle is a ZIP file containing PEM and DER
        formatted keys that permit authenticating to the deployment as the
        `materialize` user.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - deployments
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/zip:
              schema:
                type: string
                format: binary
          description: ''
  /api/deployments/{id}/logs:
    get:
      operationId: deploymentsLogsRetrieve
      description: Retrieve the logs for a deployment.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: query
        name: previous
        schema:
          type: boolean
          default: false
      tags:
      - deployments
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: ''
  /api/deployments/{id}/tailscale_logs:
    get:
      operationId: deploymentsTailscaleLogsRetrieve
      description: Retrieve the logs for a Tailscale container.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: query
        name: previous
        schema:
          type: boolean
          default: false
      tags:
      - deployments
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: ''
  /api/health:
    get:
      operationId: healthRetrieve
      description: |-
        Basic health check endpoint.

        This endpoint always returns 200 OK. It is intended for use by load
        balancers and such that need a basic indication as to whether the server is
        live.
      tags:
      - health
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/mz-versions:
    get:
      operationId: mzVersionsList
      description: |-
        List the versions of Materialize known to Materialize Cloud.

        Versions are listed in order from oldest to newest.
      tags:
      - mz-versions
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
          description: ''
  /api/mz-versions/latest:
    get:
      operationId: mzVersionsLatestRetrieve
      description: Returns the latest version of Materialize.
      parameters:
      - in: query
        name: track
        schema:
          type: string
          default: stable
      tags:
      - mz-versions
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
          description: ''
  /api/onboarding-call:
    get:
      operationId: onboardingCallRetrieve
      description: Retrieve the first scheduled onboarding call for a user.
      tags:
      - onboarding-call
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardingCall'
          description: ''
  /api/organizations/{id}:
    get:
      operationId: organizationsRetrieve
      description: Fetch details about a single organization.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this organization.
        required: true
      tags:
      - organizations
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
          description: ''
  /api/schema:
    get:
      operationId: schemaRetrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      tags:
      - schema
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Deployment:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        organization:
          type: string
          format: uuid
          readOnly: true
        tlsAuthority:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
        hostname:
          type: string
          readOnly: true
          nullable: true
        flaggedForDeletion:
          type: boolean
          readOnly: true
        flaggedForUpdate:
          type: boolean
          readOnly: true
        size:
          allOf:
          - $ref: '#/components/schemas/DeploymentSizeEnum'
          default: XS
        storageMb:
          type: integer
          maximum: 1000000
          minimum: 100
          default: 100
        disableUserIndexes:
          type: boolean
          default: false
        materializedExtraArgs:
          type: array
          items:
            type: string
            maxLength: 255
          title: Extra materialized arguments
        clusterId:
          type: string
          format: uuid
          readOnly: true
          nullable: true
        mzVersion:
          type: string
        pendingMigration:
          allOf:
          - $ref: '#/components/schemas/PendingMigration'
          readOnly: true
          nullable: true
        status:
          type: string
          readOnly: true
        enableTailscale:
          type: boolean
          default: false
      required:
      - clusterId
      - disableUserIndexes
      - enableTailscale
      - flaggedForDeletion
      - flaggedForUpdate
      - hostname
      - id
      - materializedExtraArgs
      - mzVersion
      - name
      - organization
      - pendingMigration
      - size
      - status
      - storageMb
      - tlsAuthority
    DeploymentRequest:
      type: object
      properties:
        name:
          type: string
        size:
          allOf:
          - $ref: '#/components/schemas/DeploymentSizeEnum'
          default: XS
        storageMb:
          type: integer
          maximum: 1000000
          minimum: 100
          default: 100
        disableUserIndexes:
          type: boolean
          default: false
        materializedExtraArgs:
          type: array
          items:
            type: string
            maxLength: 255
          title: Extra materialized arguments
        mzVersion:
          type: string
        enableTailscale:
          type: boolean
          default: false
        tailscaleAuthKey:
          type: string
          writeOnly: true
    DeploymentSizeEnum:
      enum:
      - XS
      - S
      - M
      - L
      - XL
      type: string
    OnboardingCall:
      type: object
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
      required:
      - end
      - start
    Organization:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        admitted:
          type: boolean
          readOnly: true
          description: Whether this organization has been admitted to Materialize
            Cloud.
        deploymentLimit:
          type: integer
          readOnly: true
        trialExpiresAt:
          type: string
          format: date-time
          readOnly: true
          nullable: true
          description: When this organization's trial period expires. If empty, the
            organization is on an enterprise plan.
      required:
      - admitted
      - deploymentLimit
      - id
      - trialExpiresAt
    PatchedDeploymentRequest:
      type: object
      properties:
        name:
          type: string
        size:
          allOf:
          - $ref: '#/components/schemas/DeploymentSizeEnum'
          default: XS
        storageMb:
          type: integer
          maximum: 1000000
          minimum: 100
          default: 100
        disableUserIndexes:
          type: boolean
          default: false
        materializedExtraArgs:
          type: array
          items:
            type: string
            maxLength: 255
          title: Extra materialized arguments
        mzVersion:
          type: string
        enableTailscale:
          type: boolean
          default: false
        tailscaleAuthKey:
          type: string
          writeOnly: true
    PendingMigration:
      type: object
      properties:
        description:
          type: string
        deadline:
          type: string
          format: date
      required:
      - deadline
      - description
    PendingMigrationRequest:
      type: object
      properties:
        description:
          type: string
        deadline:
          type: string
          format: date
      required:
      - deadline
      - description
  securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
servers: [{url: 'https://cloud.materialize.com'}]
