/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentRequest {
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<crate::models::DeploymentSize>,
    #[serde(rename = "mzVersion")]
    pub mz_version: String,
}

impl DeploymentRequest {
    pub fn new(mz_version: String) -> DeploymentRequest {
        DeploymentRequest {
            size: None,
            mz_version,
        }
    }
}


