/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoricalDeploymentDelta {
    #[serde(rename = "changes")]
    pub changes: Box<crate::models::HistoricalDeploymentChange>,
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::models::HistoricalDeploymentMetadata>,
}

impl HistoricalDeploymentDelta {
    pub fn new(
        changes: crate::models::HistoricalDeploymentChange,
        metadata: crate::models::HistoricalDeploymentMetadata,
    ) -> HistoricalDeploymentDelta {
        HistoricalDeploymentDelta {
            changes: Box::new(changes),
            metadata: Box::new(metadata),
        }
    }
}
