/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoricalDeploymentChange {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<crate::models::ModifiedString>>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<Box<crate::models::ModifiedString>>,
    #[serde(rename = "flaggedForDeletion", skip_serializing_if = "Option::is_none")]
    pub flagged_for_deletion: Option<Box<crate::models::ModifiedBoolean>>,
    #[serde(rename = "flaggedForUpdate", skip_serializing_if = "Option::is_none")]
    pub flagged_for_update: Option<Box<crate::models::ModifiedBoolean>>,
    #[serde(rename = "catalogRestoreMode", skip_serializing_if = "Option::is_none")]
    pub catalog_restore_mode: Option<Box<crate::models::ModifiedBoolean>>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<Box<crate::models::ModifiedSize>>,
    #[serde(
        rename = "materializedExtraArgs",
        skip_serializing_if = "Option::is_none"
    )]
    pub materialized_extra_args: Option<Box<crate::models::ModifiedStringList>>,
    #[serde(rename = "clusterId", skip_serializing_if = "Option::is_none")]
    pub cluster_id: Option<Box<crate::models::ModifiedString>>,
    #[serde(rename = "mzVersion", skip_serializing_if = "Option::is_none")]
    pub mz_version: Option<Box<crate::models::ModifiedString>>,
    #[serde(rename = "enableTailscale", skip_serializing_if = "Option::is_none")]
    pub enable_tailscale: Option<Box<crate::models::ModifiedBoolean>>,
}

impl HistoricalDeploymentChange {
    pub fn new() -> HistoricalDeploymentChange {
        HistoricalDeploymentChange {
            name: None,
            hostname: None,
            flagged_for_deletion: None,
            flagged_for_update: None,
            catalog_restore_mode: None,
            size: None,
            materialized_extra_args: None,
            cluster_id: None,
            mz_version: None,
            enable_tailscale: None,
        }
    }
}
