/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoricalDeploymentMetadata {
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "user")]
    pub user: String,
    #[serde(rename = "operation")]
    pub operation: Box<crate::models::OperationEnum>,
}

impl HistoricalDeploymentMetadata {
    pub fn new(
        date: String,
        user: String,
        operation: crate::models::OperationEnum,
    ) -> HistoricalDeploymentMetadata {
        HistoricalDeploymentMetadata {
            date,
            user,
            operation: Box::new(operation),
        }
    }
}
