/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifiedStringList {
    #[serde(rename = "old")]
    pub old: Vec<String>,
    #[serde(rename = "new")]
    pub new: Vec<String>,
}

impl ModifiedStringList {
    pub fn new(old: Vec<String>, new: Vec<String>) -> ModifiedStringList {
        ModifiedStringList { old, new }
    }
}
