/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifiedString {
    #[serde(rename = "old")]
    pub old: Option<String>,
    #[serde(rename = "new")]
    pub new: Option<String>,
}

impl ModifiedString {
    pub fn new(old: Option<String>, new: Option<String>) -> ModifiedString {
        ModifiedString { old, new }
    }
}
