/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifiedBoolean {
    #[serde(rename = "old")]
    pub old: Option<bool>,
    #[serde(rename = "new")]
    pub new: Option<bool>,
}

impl ModifiedBoolean {
    pub fn new(old: Option<bool>, new: Option<bool>) -> ModifiedBoolean {
        ModifiedBoolean { old, new }
    }
}
