/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifiedSize {
    #[serde(rename = "old")]
    pub old: crate::models::DeploymentSizeEnum,
    #[serde(rename = "new")]
    pub new: crate::models::DeploymentSizeEnum,
}

impl ModifiedSize {
    pub fn new(
        old: crate::models::DeploymentSizeEnum,
        new: crate::models::DeploymentSizeEnum,
    ) -> ModifiedSize {
        ModifiedSize { old, new }
    }
}
