/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OperationEnum {
    #[serde(rename = "CREATE")]
    CREATE,
    #[serde(rename = "UPDATE")]
    UPDATE,
    #[serde(rename = "DELETE")]
    DELETE,
}

impl ToString for OperationEnum {
    fn to_string(&self) -> String {
        match self {
            Self::CREATE => String::from("CREATE"),
            Self::UPDATE => String::from("UPDATE"),
            Self::DELETE => String::from("DELETE"),
        }
    }
}
