/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Organization {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "deploymentLimit")]
    pub deployment_limit: i32,
}

impl Organization {
    pub fn new(id: String, deployment_limit: i32) -> Organization {
        Organization {
            id,
            deployment_limit,
        }
    }
}


