/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Organization {
    #[serde(rename = "id")]
    pub id: String,
    /// Whether this organization has been admitted to Materialize Cloud.
    #[serde(rename = "admitted")]
    pub admitted: bool,
    #[serde(rename = "deploymentLimit")]
    pub deployment_limit: i32,
    /// When this organization's trial period expires. If empty, the organization is on an enterprise plan.
    #[serde(rename = "trialExpiresAt")]
    pub trial_expires_at: Option<String>,
}

impl Organization {
    pub fn new(id: String, admitted: bool, deployment_limit: i32, trial_expires_at: Option<String>) -> Organization {
        Organization {
            id,
            admitted,
            deployment_limit,
            trial_expires_at,
        }
    }
}


