/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingMigrationRequest {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "deadline")]
    pub deadline: String,
}

impl PendingMigrationRequest {
    pub fn new(description: String, deadline: String) -> PendingMigrationRequest {
        PendingMigrationRequest {
            description,
            deadline,
        }
    }
}
