/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PrometheusMetrics : Serializer for the prometheus metrics.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrometheusMetrics {
    #[serde(rename = "metrics")]
    pub metrics: Vec<crate::models::PrometheusMetric>,
}

impl PrometheusMetrics {
    /// Serializer for the prometheus metrics.
    pub fn new(metrics: Vec<crate::models::PrometheusMetric>) -> PrometheusMetrics {
        PrometheusMetrics { metrics }
    }
}
