/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProviderEnum {
    #[serde(rename = "AWS")]
    AWS,
}

impl ToString for ProviderEnum {
    fn to_string(&self) -> String {
        match self {
            Self::AWS => String::from("AWS"),
        }
    }
}
