/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReleaseTrackEnum {
    #[serde(rename = "canary")]
    Canary,
    #[serde(rename = "stable")]
    Stable,
}

impl ToString for ReleaseTrackEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Canary => String::from("canary"),
            Self::Stable => String::from("stable"),
        }
    }
}
