/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupportedCloudRegionRequest {
    #[serde(rename = "provider")]
    pub provider: crate::models::ProviderEnum,
    #[serde(rename = "region")]
    pub region: String,
}

impl SupportedCloudRegionRequest {
    pub fn new(
        provider: crate::models::ProviderEnum,
        region: String,
    ) -> SupportedCloudRegionRequest {
        SupportedCloudRegionRequest { provider, region }
    }
}
