/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// The unique ID assigned to this user by AWS Cognito.
    #[serde(rename = "cognitoSub")]
    pub cognito_sub: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email")]
    pub email: String,
}

impl User {
    pub fn new(cognito_sub: String, name: String, email: String) -> User {
        User {
            cognito_sub,
            name,
            email,
        }
    }
}


