/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mzcloud

import (
	"encoding/json"
)

// ModifiedBoolean struct for ModifiedBoolean
type ModifiedBoolean struct {
	Old NullableBool `json:"old"`
	New NullableBool `json:"new"`
}

// NewModifiedBoolean instantiates a new ModifiedBoolean object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifiedBoolean(old NullableBool, new NullableBool) *ModifiedBoolean {
	this := ModifiedBoolean{}
	this.Old = old
	this.New = new
	return &this
}

// NewModifiedBooleanWithDefaults instantiates a new ModifiedBoolean object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifiedBooleanWithDefaults() *ModifiedBoolean {
	this := ModifiedBoolean{}
	return &this
}

// GetOld returns the Old field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *ModifiedBoolean) GetOld() bool {
	if o == nil || o.Old.Get() == nil {
		var ret bool
		return ret
	}

	return *o.Old.Get()
}

// GetOldOk returns a tuple with the Old field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModifiedBoolean) GetOldOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Old.Get(), o.Old.IsSet()
}

// SetOld sets field value
func (o *ModifiedBoolean) SetOld(v bool) {
	o.Old.Set(&v)
}

// GetNew returns the New field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *ModifiedBoolean) GetNew() bool {
	if o == nil || o.New.Get() == nil {
		var ret bool
		return ret
	}

	return *o.New.Get()
}

// GetNewOk returns a tuple with the New field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModifiedBoolean) GetNewOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.New.Get(), o.New.IsSet()
}

// SetNew sets field value
func (o *ModifiedBoolean) SetNew(v bool) {
	o.New.Set(&v)
}

func (o ModifiedBoolean) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["old"] = o.Old.Get()
	}
	if true {
		toSerialize["new"] = o.New.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableModifiedBoolean struct {
	value *ModifiedBoolean
	isSet bool
}

func (v NullableModifiedBoolean) Get() *ModifiedBoolean {
	return v.value
}

func (v *NullableModifiedBoolean) Set(val *ModifiedBoolean) {
	v.value = val
	v.isSet = true
}

func (v NullableModifiedBoolean) IsSet() bool {
	return v.isSet
}

func (v *NullableModifiedBoolean) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifiedBoolean(val *ModifiedBoolean) *NullableModifiedBoolean {
	return &NullableModifiedBoolean{value: val, isSet: true}
}

func (v NullableModifiedBoolean) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifiedBoolean) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


