/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mzcloud

import (
	"encoding/json"
	"time"
)

// OnboardingCall struct for OnboardingCall
type OnboardingCall struct {
	Start time.Time `json:"start"`
	End time.Time `json:"end"`
}

// NewOnboardingCall instantiates a new OnboardingCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnboardingCall(start time.Time, end time.Time) *OnboardingCall {
	this := OnboardingCall{}
	this.Start = start
	this.End = end
	return &this
}

// NewOnboardingCallWithDefaults instantiates a new OnboardingCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnboardingCallWithDefaults() *OnboardingCall {
	this := OnboardingCall{}
	return &this
}

// GetStart returns the Start field value
func (o *OnboardingCall) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *OnboardingCall) GetStartOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *OnboardingCall) SetStart(v time.Time) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *OnboardingCall) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *OnboardingCall) GetEndOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *OnboardingCall) SetEnd(v time.Time) {
	o.End = v
}

func (o OnboardingCall) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["start"] = o.Start
	}
	if true {
		toSerialize["end"] = o.End
	}
	return json.Marshal(toSerialize)
}

type NullableOnboardingCall struct {
	value *OnboardingCall
	isSet bool
}

func (v NullableOnboardingCall) Get() *OnboardingCall {
	return v.value
}

func (v *NullableOnboardingCall) Set(val *OnboardingCall) {
	v.value = val
	v.isSet = true
}

func (v NullableOnboardingCall) IsSet() bool {
	return v.isSet
}

func (v *NullableOnboardingCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnboardingCall(val *OnboardingCall) *NullableOnboardingCall {
	return &NullableOnboardingCall{value: val, isSet: true}
}

func (v NullableOnboardingCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnboardingCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


