/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mzcloud

import (
	"encoding/json"
)

// PendingMigration struct for PendingMigration
type PendingMigration struct {
	Description string `json:"description"`
	Deadline string `json:"deadline"`
}

// NewPendingMigration instantiates a new PendingMigration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPendingMigration(description string, deadline string) *PendingMigration {
	this := PendingMigration{}
	this.Description = description
	this.Deadline = deadline
	return &this
}

// NewPendingMigrationWithDefaults instantiates a new PendingMigration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPendingMigrationWithDefaults() *PendingMigration {
	this := PendingMigration{}
	return &this
}

// GetDescription returns the Description field value
func (o *PendingMigration) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PendingMigration) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PendingMigration) SetDescription(v string) {
	o.Description = v
}

// GetDeadline returns the Deadline field value
func (o *PendingMigration) GetDeadline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value
// and a boolean to check if the value has been set.
func (o *PendingMigration) GetDeadlineOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Deadline, true
}

// SetDeadline sets field value
func (o *PendingMigration) SetDeadline(v string) {
	o.Deadline = v
}

func (o PendingMigration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["deadline"] = o.Deadline
	}
	return json.Marshal(toSerialize)
}

type NullablePendingMigration struct {
	value *PendingMigration
	isSet bool
}

func (v NullablePendingMigration) Get() *PendingMigration {
	return v.value
}

func (v *NullablePendingMigration) Set(val *PendingMigration) {
	v.value = val
	v.isSet = true
}

func (v NullablePendingMigration) IsSet() bool {
	return v.isSet
}

func (v *NullablePendingMigration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePendingMigration(val *PendingMigration) *NullablePendingMigration {
	return &NullablePendingMigration{value: val, isSet: true}
}

func (v NullablePendingMigration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePendingMigration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


