/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mzcloud

import (
	"encoding/json"
)

// PatchedDeploymentUpdateRequest struct for PatchedDeploymentUpdateRequest
type PatchedDeploymentUpdateRequest struct {
	Name *string `json:"name,omitempty"`
	Size *DeploymentSizeEnum `json:"size,omitempty"`
	StorageMb *int32 `json:"storageMb,omitempty"`
	DisableUserIndexes *bool `json:"disableUserIndexes,omitempty"`
	MaterializedExtraArgs *[]string `json:"materializedExtraArgs,omitempty"`
	MzVersion *string `json:"mzVersion,omitempty"`
	EnableTailscale *bool `json:"enableTailscale,omitempty"`
	TailscaleAuthKey *string `json:"tailscaleAuthKey,omitempty"`
}

// NewPatchedDeploymentUpdateRequest instantiates a new PatchedDeploymentUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedDeploymentUpdateRequest() *PatchedDeploymentUpdateRequest {
	this := PatchedDeploymentUpdateRequest{}
	var storageMb int32 = 100
	this.StorageMb = &storageMb
	var disableUserIndexes bool = false
	this.DisableUserIndexes = &disableUserIndexes
	var enableTailscale bool = false
	this.EnableTailscale = &enableTailscale
	return &this
}

// NewPatchedDeploymentUpdateRequestWithDefaults instantiates a new PatchedDeploymentUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedDeploymentUpdateRequestWithDefaults() *PatchedDeploymentUpdateRequest {
	this := PatchedDeploymentUpdateRequest{}
	var storageMb int32 = 100
	this.StorageMb = &storageMb
	var disableUserIndexes bool = false
	this.DisableUserIndexes = &disableUserIndexes
	var enableTailscale bool = false
	this.EnableTailscale = &enableTailscale
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedDeploymentUpdateRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDeploymentUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedDeploymentUpdateRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedDeploymentUpdateRequest) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *PatchedDeploymentUpdateRequest) GetSize() DeploymentSizeEnum {
	if o == nil || o.Size == nil {
		var ret DeploymentSizeEnum
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDeploymentUpdateRequest) GetSizeOk() (*DeploymentSizeEnum, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PatchedDeploymentUpdateRequest) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given DeploymentSizeEnum and assigns it to the Size field.
func (o *PatchedDeploymentUpdateRequest) SetSize(v DeploymentSizeEnum) {
	o.Size = &v
}

// GetStorageMb returns the StorageMb field value if set, zero value otherwise.
func (o *PatchedDeploymentUpdateRequest) GetStorageMb() int32 {
	if o == nil || o.StorageMb == nil {
		var ret int32
		return ret
	}
	return *o.StorageMb
}

// GetStorageMbOk returns a tuple with the StorageMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDeploymentUpdateRequest) GetStorageMbOk() (*int32, bool) {
	if o == nil || o.StorageMb == nil {
		return nil, false
	}
	return o.StorageMb, true
}

// HasStorageMb returns a boolean if a field has been set.
func (o *PatchedDeploymentUpdateRequest) HasStorageMb() bool {
	if o != nil && o.StorageMb != nil {
		return true
	}

	return false
}

// SetStorageMb gets a reference to the given int32 and assigns it to the StorageMb field.
func (o *PatchedDeploymentUpdateRequest) SetStorageMb(v int32) {
	o.StorageMb = &v
}

// GetDisableUserIndexes returns the DisableUserIndexes field value if set, zero value otherwise.
func (o *PatchedDeploymentUpdateRequest) GetDisableUserIndexes() bool {
	if o == nil || o.DisableUserIndexes == nil {
		var ret bool
		return ret
	}
	return *o.DisableUserIndexes
}

// GetDisableUserIndexesOk returns a tuple with the DisableUserIndexes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDeploymentUpdateRequest) GetDisableUserIndexesOk() (*bool, bool) {
	if o == nil || o.DisableUserIndexes == nil {
		return nil, false
	}
	return o.DisableUserIndexes, true
}

// HasDisableUserIndexes returns a boolean if a field has been set.
func (o *PatchedDeploymentUpdateRequest) HasDisableUserIndexes() bool {
	if o != nil && o.DisableUserIndexes != nil {
		return true
	}

	return false
}

// SetDisableUserIndexes gets a reference to the given bool and assigns it to the DisableUserIndexes field.
func (o *PatchedDeploymentUpdateRequest) SetDisableUserIndexes(v bool) {
	o.DisableUserIndexes = &v
}

// GetMaterializedExtraArgs returns the MaterializedExtraArgs field value if set, zero value otherwise.
func (o *PatchedDeploymentUpdateRequest) GetMaterializedExtraArgs() []string {
	if o == nil || o.MaterializedExtraArgs == nil {
		var ret []string
		return ret
	}
	return *o.MaterializedExtraArgs
}

// GetMaterializedExtraArgsOk returns a tuple with the MaterializedExtraArgs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDeploymentUpdateRequest) GetMaterializedExtraArgsOk() (*[]string, bool) {
	if o == nil || o.MaterializedExtraArgs == nil {
		return nil, false
	}
	return o.MaterializedExtraArgs, true
}

// HasMaterializedExtraArgs returns a boolean if a field has been set.
func (o *PatchedDeploymentUpdateRequest) HasMaterializedExtraArgs() bool {
	if o != nil && o.MaterializedExtraArgs != nil {
		return true
	}

	return false
}

// SetMaterializedExtraArgs gets a reference to the given []string and assigns it to the MaterializedExtraArgs field.
func (o *PatchedDeploymentUpdateRequest) SetMaterializedExtraArgs(v []string) {
	o.MaterializedExtraArgs = &v
}

// GetMzVersion returns the MzVersion field value if set, zero value otherwise.
func (o *PatchedDeploymentUpdateRequest) GetMzVersion() string {
	if o == nil || o.MzVersion == nil {
		var ret string
		return ret
	}
	return *o.MzVersion
}

// GetMzVersionOk returns a tuple with the MzVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDeploymentUpdateRequest) GetMzVersionOk() (*string, bool) {
	if o == nil || o.MzVersion == nil {
		return nil, false
	}
	return o.MzVersion, true
}

// HasMzVersion returns a boolean if a field has been set.
func (o *PatchedDeploymentUpdateRequest) HasMzVersion() bool {
	if o != nil && o.MzVersion != nil {
		return true
	}

	return false
}

// SetMzVersion gets a reference to the given string and assigns it to the MzVersion field.
func (o *PatchedDeploymentUpdateRequest) SetMzVersion(v string) {
	o.MzVersion = &v
}

// GetEnableTailscale returns the EnableTailscale field value if set, zero value otherwise.
func (o *PatchedDeploymentUpdateRequest) GetEnableTailscale() bool {
	if o == nil || o.EnableTailscale == nil {
		var ret bool
		return ret
	}
	return *o.EnableTailscale
}

// GetEnableTailscaleOk returns a tuple with the EnableTailscale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDeploymentUpdateRequest) GetEnableTailscaleOk() (*bool, bool) {
	if o == nil || o.EnableTailscale == nil {
		return nil, false
	}
	return o.EnableTailscale, true
}

// HasEnableTailscale returns a boolean if a field has been set.
func (o *PatchedDeploymentUpdateRequest) HasEnableTailscale() bool {
	if o != nil && o.EnableTailscale != nil {
		return true
	}

	return false
}

// SetEnableTailscale gets a reference to the given bool and assigns it to the EnableTailscale field.
func (o *PatchedDeploymentUpdateRequest) SetEnableTailscale(v bool) {
	o.EnableTailscale = &v
}

// GetTailscaleAuthKey returns the TailscaleAuthKey field value if set, zero value otherwise.
func (o *PatchedDeploymentUpdateRequest) GetTailscaleAuthKey() string {
	if o == nil || o.TailscaleAuthKey == nil {
		var ret string
		return ret
	}
	return *o.TailscaleAuthKey
}

// GetTailscaleAuthKeyOk returns a tuple with the TailscaleAuthKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDeploymentUpdateRequest) GetTailscaleAuthKeyOk() (*string, bool) {
	if o == nil || o.TailscaleAuthKey == nil {
		return nil, false
	}
	return o.TailscaleAuthKey, true
}

// HasTailscaleAuthKey returns a boolean if a field has been set.
func (o *PatchedDeploymentUpdateRequest) HasTailscaleAuthKey() bool {
	if o != nil && o.TailscaleAuthKey != nil {
		return true
	}

	return false
}

// SetTailscaleAuthKey gets a reference to the given string and assigns it to the TailscaleAuthKey field.
func (o *PatchedDeploymentUpdateRequest) SetTailscaleAuthKey(v string) {
	o.TailscaleAuthKey = &v
}

func (o PatchedDeploymentUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.StorageMb != nil {
		toSerialize["storageMb"] = o.StorageMb
	}
	if o.DisableUserIndexes != nil {
		toSerialize["disableUserIndexes"] = o.DisableUserIndexes
	}
	if o.MaterializedExtraArgs != nil {
		toSerialize["materializedExtraArgs"] = o.MaterializedExtraArgs
	}
	if o.MzVersion != nil {
		toSerialize["mzVersion"] = o.MzVersion
	}
	if o.EnableTailscale != nil {
		toSerialize["enableTailscale"] = o.EnableTailscale
	}
	if o.TailscaleAuthKey != nil {
		toSerialize["tailscaleAuthKey"] = o.TailscaleAuthKey
	}
	return json.Marshal(toSerialize)
}

type NullablePatchedDeploymentUpdateRequest struct {
	value *PatchedDeploymentUpdateRequest
	isSet bool
}

func (v NullablePatchedDeploymentUpdateRequest) Get() *PatchedDeploymentUpdateRequest {
	return v.value
}

func (v *NullablePatchedDeploymentUpdateRequest) Set(val *PatchedDeploymentUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedDeploymentUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedDeploymentUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedDeploymentUpdateRequest(val *PatchedDeploymentUpdateRequest) *NullablePatchedDeploymentUpdateRequest {
	return &NullablePatchedDeploymentUpdateRequest{value: val, isSet: true}
}

func (v NullablePatchedDeploymentUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedDeploymentUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


