/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mzcloud

import (
	"encoding/json"
)

// PendingMigrationRequest struct for PendingMigrationRequest
type PendingMigrationRequest struct {
	Description string `json:"description"`
	Deadline string `json:"deadline"`
}

// NewPendingMigrationRequest instantiates a new PendingMigrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPendingMigrationRequest(description string, deadline string) *PendingMigrationRequest {
	this := PendingMigrationRequest{}
	this.Description = description
	this.Deadline = deadline
	return &this
}

// NewPendingMigrationRequestWithDefaults instantiates a new PendingMigrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPendingMigrationRequestWithDefaults() *PendingMigrationRequest {
	this := PendingMigrationRequest{}
	return &this
}

// GetDescription returns the Description field value
func (o *PendingMigrationRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PendingMigrationRequest) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PendingMigrationRequest) SetDescription(v string) {
	o.Description = v
}

// GetDeadline returns the Deadline field value
func (o *PendingMigrationRequest) GetDeadline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value
// and a boolean to check if the value has been set.
func (o *PendingMigrationRequest) GetDeadlineOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Deadline, true
}

// SetDeadline sets field value
func (o *PendingMigrationRequest) SetDeadline(v string) {
	o.Deadline = v
}

func (o PendingMigrationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["deadline"] = o.Deadline
	}
	return json.Marshal(toSerialize)
}

type NullablePendingMigrationRequest struct {
	value *PendingMigrationRequest
	isSet bool
}

func (v NullablePendingMigrationRequest) Get() *PendingMigrationRequest {
	return v.value
}

func (v *NullablePendingMigrationRequest) Set(val *PendingMigrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePendingMigrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePendingMigrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePendingMigrationRequest(val *PendingMigrationRequest) *NullablePendingMigrationRequest {
	return &NullablePendingMigrationRequest{value: val, isSet: true}
}

func (v NullablePendingMigrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePendingMigrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


