/*
 * Materialize Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mzcloud

import (
	"encoding/json"
	"fmt"
)

// SizeEnum the model 'SizeEnum'
type SizeEnum string

// List of SizeEnum
const (
	XS SizeEnum = "XS"
	S SizeEnum = "S"
	M SizeEnum = "M"
	L SizeEnum = "L"
	XL SizeEnum = "XL"
)

var allowedSizeEnumEnumValues = []SizeEnum{
	"XS",
	"S",
	"M",
	"L",
	"XL",
}

func (v *SizeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SizeEnum(value)
	for _, existing := range allowedSizeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SizeEnum", value)
}

// NewSizeEnumFromValue returns a pointer to a valid SizeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSizeEnumFromValue(v string) (*SizeEnum, error) {
	ev := SizeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SizeEnum: valid values are %v", v, allowedSizeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SizeEnum) IsValid() bool {
	for _, existing := range allowedSizeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SizeEnum value
func (v SizeEnum) Ptr() *SizeEnum {
	return &v
}

type NullableSizeEnum struct {
	value *SizeEnum
	isSet bool
}

func (v NullableSizeEnum) Get() *SizeEnum {
	return v.value
}

func (v *NullableSizeEnum) Set(val *SizeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableSizeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableSizeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSizeEnum(val *SizeEnum) *NullableSizeEnum {
	return &NullableSizeEnum{value: val, isSet: true}
}

func (v NullableSizeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSizeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

